---
# These ansible tasks will 
# (1) clone the latest upstream SCAP Security Guide
#     and place it into /var/www/html/scap-security-guide
# (2) 'make' RHEL7 content
# (3) install course RPMs, if applicable

- name: Update file permissions on /var/www/
  become: yes
  command: chmod -R 755 /var/www/

- name: Update file ownership on /var/www/
  become: yes
  command: chown -R ec2-user /var/www/

- name: Clone upstream SCAP Security Guide
  become: no 
  git: accept_hostkey=yes  clone=yes  dest=/var/www/html/scap-security-guide/ repo=https://github.com/OpenSCAP/scap-security-guide.git

- name: Compile SCAP Security Guide's RHEL7 Content
  become: no
  command: make chdir=/var/www/html/scap-security-guide/

- name: Update file permissions on /var/www/
  become: yes
  command: chmod -R 755 /var/www/

- name: Update file ownership on /var/www/
  become: yes
  command: chown -R ec2-user /var/www/

# cheating. much faster to make rpm local, post, and have VMs download
# as opposed to make rpm on student machines!
- name: Download & install course SSG content
  become: yes
  command: yum -y install http://people.redhat.com/swells/scap-security-guide-0.1.30.1.201611161739GIT619011d-1.el7.noarch.rpm 
  ignore_errors: yes

- name: Download and install course SSG docs
  become: yes
  command: yum -y install http://people.redhat.com/swells/scap-security-guide-doc-0.1.30.1.201611161739GIT619011d-1.el7.noarch.rpm
  ignore_errors: yes

- name: Copy docs to apache
  become: no
  command: cp -r /usr/share/doc/scap-security-guide/ /var/www/html/docs/

