---

#---------------------------------------------------
#  Update System
#---------------------------------------------------

- name: Install EPEL
  command: yum-config-manager --enable rhui-REGION-rhel-server-extras

# - name: Update all yum packages
#   yum: name=* state=latest
#   tags:
#     - rhel

- name: Install pre requisites
  yum: name={{ item }} state=present
  with_items:
      - wget
      - vim
      - git
      - unzip
      - httpd-tools
      - httpd
      - openscap-utils
      - python-lxml
  tags:
    - rhel

- name: Update all yum packages
  yum: name=* state=latest
  tags:
    - rhel

- name: Enable and Start Apache
  service: name=httpd enabled=yes state=started 
  tags:
    - rhel

#- name: Remove default welcome.conf
#  file: path=/etc/httpd/welcome state=absent
#    - rhel

- name: Copy website to Apache dir
  copy: src=web_content/index.html dest=/var/www/html/index.html mode=0755 owner=ec2-user
  tags:
    - rhel

- name: Copy website CSS to Apache dir
  copy: src=web_content/css dest=/var/www/html/ mode=0755 owner=ec2-user
  tags:
    - rhel


- name: Copy website images to Apache dir
  copy: src=web_content/img dest=/var/www/html/ mode=0755 owner=ec2-user
  tags:
    - rhel

- name: Reload Apache
  command: service httpd restart
  tags:
    - rhel

#---------------------------------------------------
#  SSH Key
#---------------------------------------------------
- name: Copy over student ssh key 
  copy: src="{{ lookup('env','HOME') }}/.ssh/container"  dest=/var/www/html/container.pem
  tags:
    - rhel